# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Hello, world!

tasks:
  format:
    desc: Format
    cmds:
      - uv run ruff check --fix .
      - uv run ruff format .
    silent: true

  dev:
    desc: Dev server
    cmds:
      - uv run fastapi dev main.py

  pro:
    desc: Production server
    cmds:
      - uv run fastapi run main.py
