"""add social authentication with user providers table updated

Revision ID: b6487ee909c3
Revises: f23983b2608c
Create Date: 2026-02-10 15:41:39.627611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6487ee909c3'
down_revision: Union[str, Sequence[str], None] = 'f23983b2608c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auth_provider_enum', sa.Enum('EMAIL', 'GOOGLE', 'FACEBOOK', name='authprovider'), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False, comment='User ID from the OAuth provider'),
    sa.Column('provider_email', sa.String(length=255), nullable=True, comment='Email from provider (may differ from user.email)'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_providers_id'), 'user_providers', ['id'], unique=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_user_providers_id'), table_name='user_providers')
    op.drop_table('user_providers')
    # ### end Alembic commands ###
